/**
 * Tool Runner — maps each tool's engine name to the actual engine function.
 * Inputs come from user form fields as Record<string, string>.
 * Returns a Record<string, any> result object.
 */
import * as E from './engines';

type ToolInputs = Record<string, string>;
type ToolResult = Record<string, any>;

export function runTool(engine: string, inputs: ToolInputs): ToolResult {
  const n = (key: string, fallback = 0) => parseFloat(inputs[key] ?? String(fallback)) || fallback;
  const s = (key: string, fallback = '') => inputs[key] ?? fallback;
  const i = (key: string, fallback = 0) => parseInt(inputs[key] ?? String(fallback)) || fallback;

  switch (engine) {
    // ---- FINANCE ----
    case 'loan_calculator': return E.calcLoan(n('principal'), n('rate'), i('term'));
    case 'mortgage_calculator': return E.calcLoan(n('principal'), n('rate'), i('term', 360));
    case 'auto_loan_calculator': return E.calcLoan(n('principal'), n('rate'), i('term', 60));
    case 'boat_loan_calculator': return E.calcLoan(n('principal'), n('rate'), i('term', 120));
    case 'rv_loan_calculator': return E.calcLoan(n('principal'), n('rate'), i('term', 120));
    case 'personal_loan_calculator': return E.calcLoan(n('principal'), n('rate'), i('term', 36));
    case 'student_loan_calculator': return E.calcLoan(n('principal'), n('rate', 5.5), i('term', 120));
    case 'car_loan_calculator': return E.calcLoan(n('principal'), n('rate'), i('term', 60));
    case 'home_equity_loan_calculator': return E.calcLoan(n('principal'), n('rate'), i('term', 120));
    case 'business_loan_calculator': return E.calcLoan(n('principal'), n('rate'), i('term', 60));
    case 'compound_interest_calculator': return E.calcCompoundInterest(n('principal'), n('rate'), n('years'), i('compounds', 12));
    case 'simple_interest_calculator': return E.calcSimpleInterest(n('principal'), n('rate'), n('years'));
    case 'retirement_calculator': return E.calcRetirement(i('current_age'), i('retire_age', 65), n('savings'), n('monthly_contrib'), n('return_rate', 7));
    case 'savings_calculator': return E.calcCompoundInterest(n('principal'), n('rate'), n('years'));
    case 'investment_return_calculator': return E.calcROI(n('final_value'), n('initial_investment'));
    case 'profit_margin_calculator': return E.calcProfitMargin(n('revenue'), n('cost'));
    case 'markup_calculator': return E.calcMarkup(n('cost'), n('markup'));
    case 'discount_calculator': return E.calcDiscount(n('price'), n('discount'));
    case 'break_even_calculator': return E.calcBreakEven(n('fixed_costs'), n('price_per_unit'), n('variable_cost'));
    case 'commission_calculator': return E.calcCommission(n('sale_amount'), n('commission_rate'));
    case 'paycheck_calculator': return E.calcPaycheck(n('hourly_rate'), n('hours', 40), n('tax_rate', 25));
    case 'hourly_to_salary_calculator': return E.calcHourlyToSalary(n('hourly_rate'), n('hours_per_week', 40));
    case 'salary_to_hourly_calculator': return E.calcSalaryToHourly(n('annual_salary'), n('hours_per_week', 40));
    case 'overtime_calculator': return E.calcOvertime(n('regular_rate'), n('regular_hours', 40), n('overtime_hours'), n('multiplier', 1.5));
    case 'apr_calculator': return E.calcAPR(n('loan_amount'), n('fees'), n('monthly_payment'), i('term', 60));
    case 'roi_calculator': return E.calcROI(n('final_value'), n('initial_investment'));
    case 'sales_tax_calculator': return E.calcSalesTax(n('price'), n('tax_rate'));
    case 'tip_calculator': return E.calcTip(n('bill'), n('tip_percent', 18), i('people', 1));
    case 'split_bill_calculator': return E.calcSplitBill(n('total'), i('people', 2), n('tip_percent', 0));
    case 'ebay_fee_calculator': return E.calcEbayFee(n('sale_price'), n('shipping', 0));
    case 'etsy_fee_calculator': return E.calcEtsyFee(n('sale_price'), n('shipping', 0));
    case 'amazon_fee_calculator': return E.calcAmazonFee(n('sale_price'), s('category', 'general'));
    case 'inventory_turnover_calculator': return E.calcInventoryTurnover(n('cogs'), n('avg_inventory'));
    case 'ad_spend_calculator': return E.calcAdSpend(n('budget'), n('cpc'), n('conversion_rate'), n('order_value'));
    case 'conversion_rate_calculator': return E.calcConversionRate(n('visitors'), n('conversions'));
    case 'ecommerce_fee_calculator': return E.calcEbayFee(n('sale_price'), n('shipping', 0));
    case 'shipping_cost_estimator': return { estimatedCost: +(n('weight') * n('rate', 0.85) + n('base', 5)).toFixed(2), note: 'Estimate only — rates vary by carrier' };
    case 'loan_payoff_calculator': return E.calcLoanPayoff(n('balance'), n('rate'), n('payment'));
    case 'fuel_cost_calculator': return E.calcFuelCost(n('miles'), n('mpg', 30), n('price_per_gallon', 3.5));
    case 'electricity_cost_calculator': return E.calcElectricityBill(n('kwh'), n('rate', 0.12), i('days', 30));

    // ---- CONSTRUCTION ----
    case 'concrete_calculator': return E.calcConcrete(n('length'), n('width'), n('depth'));
    case 'concrete_slab_calculator': return E.calcConcrete(n('length'), n('width'), n('depth', 4));
    case 'concrete_footing_calculator': return E.calcConcreteFooting(n('diameter'), n('depth'), i('footings', 4));
    case 'gravel_calculator': return E.calcGravel(n('length'), n('width'), n('depth', 3));
    case 'mulch_calculator': return E.calcMulch(n('length'), n('width'), n('depth', 3));
    case 'paint_calculator': return E.calcPaint(n('length'), n('width'), n('height', 9), i('doors', 0), i('windows', 0), i('coats', 2));
    case 'fence_calculator': return E.calcFence(n('linear_feet'), n('post_spacing', 8));
    case 'deck_board_calculator': return E.calcDeckBoards(n('length'), n('width'));
    case 'tile_calculator': return E.calcTile(n('length'), n('width'), n('tile_size', 12));
    case 'flooring_calculator': return E.calcFlooring(n('length'), n('width'), n('waste', 10));
    case 'roofing_calculator': return E.calcRoofing(n('length'), n('width'), n('pitch', 4));
    case 'drywall_calculator': return E.calcDrywall(n('length'), n('width'), n('height', 9));
    case 'brick_calculator': return E.calcBrick(n('length'), n('height'));
    case 'rebar_calculator': return E.calcRebar(n('length'), n('width'), n('spacing', 12));
    case 'staircase_calculator': return E.calcStaircase(n('total_rise'), n('riser_height', 7));
    case 'square_footage_calculator': return E.calcSquareFootage(n('length'), n('width'));
    case 'topsoil_calculator': return E.calcGravel(n('length'), n('width'), n('depth', 4));
    case 'sand_calculator': return E.calcGravel(n('length'), n('width'), n('depth', 2));
    case 'asphalt_calculator': return { ...E.calcConcrete(n('length'), n('width'), n('depth', 2)), tons: +( n('length') * n('width') * (n('depth',2)/12) / 27 * 2.025 ).toFixed(2) };
    case 'patio_calculator': return E.calcSquareFootage(n('length'), n('width'));
    case 'siding_calculator': return E.calcPaint(n('length'), n('width'), n('height', 10));
    case 'wallpaper_calculator': return { ...E.calcPaint(n('length'), n('width'), n('height', 9)), rolls: Math.ceil(E.calcPaint(n('length'), n('width'), n('height',9)).paintableArea / 56) };
    case 'lumber_calculator': return { boardFeet: +((n('pieces') * n('thickness') * n('width_in') * n('length_ft')) / 12).toFixed(2) };
    case 'cubic_yards_calculator': return { cubicYards: +((n('length') * n('width') * (n('depth')/12)) / 27).toFixed(3) };
    case 'retaining_wall_calculator': return { blocks: Math.ceil(n('length') * n('height') * 0.75), note: 'Approximate — consult a contractor' };

    // ---- CONVERTERS ----
    case 'inches_to_cm': return E.inchesToCm(n('value'));
    case 'cm_to_inches': return E.cmToInches(n('value'));
    case 'feet_to_meters': return E.feetToMeters(n('value'));
    case 'meters_to_feet': return E.metersToFeet(n('value'));
    case 'miles_to_km': return E.milesToKm(n('value'));
    case 'km_to_miles': return E.kmToMiles(n('value'));
    case 'pounds_to_kg': return E.poundsToKg(n('value'));
    case 'kg_to_pounds': return E.kgToPounds(n('value'));
    case 'celsius_to_fahrenheit': return E.celsiusToFahrenheit(n('value'));
    case 'fahrenheit_to_celsius': return E.fahrenheitToCelsius(n('value'));
    case 'gallons_to_liters': return E.gallonsToLiters(n('value'));
    case 'liters_to_gallons': return E.litersToGallons(n('value'));
    case 'ounces_to_grams': return E.ouncesToGrams(n('value'));
    case 'grams_to_ounces': return E.gramsToOunces(n('value'));
    case 'psi_to_bar': return E.psiToBar(n('value'));
    case 'bar_to_psi': return E.barToPsi(n('value'));
    case 'mph_to_kph': return E.mphToKph(n('value'));
    case 'kph_to_mph': return E.kphToMph(n('value'));
    case 'acres_to_sq_ft': return E.acresToSqFt(n('value'));
    case 'sq_ft_to_acres': return E.sqFtToAcres(n('value'));
    case 'sq_ft_to_sq_m': return E.sqFtToSqM(n('value'));
    case 'sq_m_to_sq_ft': return E.sqMToSqFt(n('value'));
    case 'celsius_to_kelvin': return E.celsiusToKelvin(n('value'));
    case 'kelvin_to_celsius': return E.kelvinToCelsius(n('value'));
    case 'fahrenheit_to_kelvin': return E.fahrenheitToKelvin(n('value'));
    case 'kelvin_to_fahrenheit': return E.kelvinToFahrenheit(n('value'));
    case 'feet_to_inches': return E.feetToInches(n('value'));
    case 'inches_to_feet': return E.inchesToFeet(n('value'));
    case 'yards_to_meters': return E.yardsToMeters(n('value'));
    case 'meters_to_yards': return E.metersToYards(n('value'));
    case 'miles_to_feet': return E.milesToFeet(n('value'));
    case 'feet_to_miles': return E.feetToMiles(n('value'));
    case 'mm_to_inches': return E.mmToInches(n('value'));
    case 'inches_to_mm': return E.inchesToMm(n('value'));
    case 'km_to_feet': return E.kmToFeet(n('value'));
    case 'feet_to_km': return E.feetToKm(n('value'));
    case 'miles_to_meters': return E.milesToMeters(n('value'));
    case 'meters_to_miles': return E.metersToMiles(n('value'));
    case 'stones_to_pounds': return E.stonesToPounds(n('value'));
    case 'pounds_to_stones': return E.poundsToStones(n('value'));
    case 'kg_to_grams': return E.kgToGrams(n('value'));
    case 'grams_to_kg': return E.gramsToKg(n('value'));
    case 'tons_to_kg': return E.tonToKg(n('value'));
    case 'kg_to_tons': return E.kgToTon(n('value'));
    case 'lbs_to_ounces': return E.lbsToOunces(n('value'));
    case 'ounces_to_lbs': return E.ouncesToLbs(n('value'));
    case 'ml_to_ounces': return E.mlToOunces(n('value'));
    case 'ounces_to_ml': return E.ouncesToMl(n('value'));
    case 'cups_to_ml': return E.cupsToMl(n('value'));
    case 'ml_to_cups': return E.mlToCups(n('value'));
    case 'liters_to_ml': return E.litersToMl(n('value'));
    case 'ml_to_liters': return E.mlToLiters(n('value'));
    case 'quarts_to_liters': return E.quartsToLiters(n('value'));
    case 'liters_to_quarts': return E.litersToQuarts(n('value'));
    case 'pints_to_ml': return E.pintsToMl(n('value'));
    case 'ml_to_pints': return E.mlToPints(n('value'));
    case 'tablespoon_to_ml': return E.tablespoonToMl(n('value'));
    case 'teaspoon_to_ml': return E.teaspoonToMl(n('value'));
    case 'cubic_feet_to_gallons': return E.cubicFeetToGallons(n('value'));
    case 'gallons_to_cubic_feet': return E.gallonsToCubicFeet(n('value'));
    case 'liters_to_ounces': return E.litersToOunces(n('value'));
    case 'hectares_to_acres': return E.hectaresToAcres(n('value'));
    case 'acres_to_hectares': return E.acresToHectares(n('value'));
    case 'sq_km_to_sq_miles': return E.sqKmToSqMiles(n('value'));
    case 'sq_miles_to_sq_km': return E.sqMilesToSqKm(n('value'));
    case 'sq_inches_to_sq_cm': return E.sqInchesToSqCm(n('value'));
    case 'sq_yards_to_sq_ft': return E.sqYardsToSqFt(n('value'));
    case 'sq_ft_to_sq_yards': return E.sqFtToSqYards(n('value'));
    case 'psi_to_kpa': return E.psiToKpa(n('value'));
    case 'kpa_to_psi': return E.kpaToPsi(n('value'));
    case 'atm_to_psi': return E.atmToPsi(n('value'));
    case 'psi_to_atm': return E.psiToAtm(n('value'));
    case 'bar_to_kpa': return E.barToKpa(n('value'));
    case 'kpa_to_bar': return E.kpaToBar(n('value'));
    case 'pa_to_kpa': return E.paToKpa(n('value'));
    case 'bar_to_atm': return E.barToAtm(n('value'));
    case 'atm_to_bar': return E.atmToBar(n('value'));
    case 'mmhg_to_psi': return E.mmhgToPsi(n('value'));
    case 'mph_to_ms': return E.mphToMs(n('value'));
    case 'ms_to_mph': return E.msToMph(n('value'));
    case 'kph_to_ms': return E.kphToMs(n('value'));
    case 'ms_to_kph': return E.msToKph(n('value'));
    case 'knots_to_mph': return E.knotsToMph(n('value'));
    case 'mph_to_knots': return E.mphToKnots(n('value'));
    case 'knots_to_kph': return E.knotsToKph(n('value'));
    case 'kph_to_knots': return E.kphToKnots(n('value'));
    case 'mph_to_fps': return E.mphToFps(n('value'));
    case 'fps_to_mph': return E.fpsToMph(n('value'));
    case 'joules_to_kcal': return E.joulestoKcal(n('value'));
    case 'kcal_to_joules': return E.kcalToJoules(n('value'));
    case 'kwh_to_joules': return E.kwhToJoules(n('value'));
    case 'joules_to_kwh': return E.joulesToKwh(n('value'));
    case 'btu_to_kwh': return E.btuToKwh(n('value'));
    case 'kwh_to_btu': return E.kwhToBtu(n('value'));
    case 'btu_to_joules': return E.btuToJoules(n('value'));
    case 'calories_to_joules': return E.caloriesToJoules(n('value'));
    case 'joules_to_calories': return E.joulesToCalories(n('value'));
    case 'gb_to_mb': return E.gbToMb(n('value'));
    case 'mb_to_gb': return E.mbToGb(n('value'));
    case 'tb_to_gb': return E.tbToGb(n('value'));
    case 'gb_to_tb': return E.gbToTb(n('value'));
    case 'mb_to_kb': return E.mbToKb(n('value'));
    case 'kb_to_mb': return E.kbToMb(n('value'));
    case 'gb_to_bytes': return E.gbToBytes(n('value'));
    case 'bytes_to_gb': return E.bytesToGb(n('value'));
    case 'kb_to_bytes': return E.kbToBytes(n('value'));
    case 'bytes_to_kb': return E.bytesToKb(n('value'));
    case 'mb_to_bytes': return E.mbToBytes(n('value'));
    case 'bytes_to_mb': return E.bytesToMb(n('value'));
    case 'tb_to_bytes': return E.tbToBytes(n('value'));
    case 'seconds_to_minutes': return E.secondsToMinutes(n('value'));
    case 'minutes_to_seconds': return E.minutesToSeconds(n('value'));
    case 'minutes_to_hours': return E.minutesToHours(n('value'));
    case 'hours_to_minutes': return E.hoursToMinutes(n('value'));
    case 'hours_to_days': return E.hoursToDays(n('value'));
    case 'days_to_hours': return E.daysToHours(n('value'));
    case 'days_to_weeks': return E.daysToWeeks(n('value'));
    case 'weeks_to_days': return E.weeksToDays(n('value'));
    case 'hours_to_seconds': return E.hoursToSeconds(n('value'));
    case 'seconds_to_hours': return E.secondsToHours(n('value'));
    case 'days_to_seconds': return E.daysToSeconds(n('value'));
    case 'weeks_to_hours': return E.weeksToHours(n('value'));
    case 'months_to_days': return E.monthsToDays(n('value'));
    case 'days_to_months': return E.daysToMonths(n('value'));
    case 'years_to_months': return E.yearsToMonths(n('value'));
    case 'months_to_years': return E.monthsToYears(n('value'));
    case 'years_to_days': return E.yearsToDays(n('value'));
    case 'days_to_years': return E.daysToYears(n('value'));
    case 'degrees_to_radians': return E.degreesToRadians(n('value'));
    case 'radians_to_degrees': return E.radiansToDegrees(n('value'));
    case 'degrees_to_gradians': return E.degreesToGradians(n('value'));
    case 'gradians_to_degrees': return E.gradiansToDegrees(n('value'));
    case 'inches_to_yards': return E.inchesToYards(n('value'));
    case 'yards_to_inches': return E.yardsToInches(n('value'));
    case 'yards_to_feet': return E.yardsToFeet(n('value'));
    case 'feet_to_yards': return E.feetToYards(n('value'));
    case 'cm_to_mm': return E.cmToMm(n('value'));
    case 'mm_to_cm': return E.mmToCm(n('value'));
    case 'cm_to_m': return E.cmToM(n('value'));
    case 'm_to_cm': return E.mToCm(n('value'));
    case 'm_to_km': return E.mToKm(n('value'));
    case 'km_to_m': return E.kmToM(n('value'));
    case 'uk_gallons_to_us_gallons': return E.ukGallonsToUsGallons(n('value'));
    case 'us_gallons_to_uk_gallons': return E.usGallonsToUkGallons(n('value'));
    case 'sq_miles_to_acres': return E.sqMilesToAcres(n('value'));
    case 'acres_to_sq_miles': return E.acresToSqMiles(n('value'));
    case 'mm_to_ft': return { result: +(n('value') * 0.00328084).toFixed(6) };
    case 'ft_to_mm': return { result: +(n('value') / 0.00328084).toFixed(2) };
    case 'ml_to_tablespoon': return E.mlToTablespoon(n('value'));
    case 'ml_to_teaspoon': return E.mlToTeaspoon(n('value'));
    case 'psi_to_mmhg': return E.psiToMmhg(n('value'));
    case 'kpa_to_pa': return E.kpaToPa(n('value'));
    case 'joules_to_btu': return E.joulesToBtu(n('value'));
    case 'ms_to_kph_converter': return E.msToKph(n('value'));
    case 'sq_cm_to_sq_inches': return E.sqCmToSqInches(n('value'));

    // ---- HEALTH ----
    case 'bmi_calculator': return E.calcBMI(n('weight'), n('height'));
    case 'calorie_calculator': return E.calcCalories(n('weight'), n('height'), i('age'), s('gender','male') as 'male'|'female', s('activity','moderately_active'));
    case 'body_fat_calculator': return E.calcBodyFat(s('gender','male') as 'male'|'female', n('waist'), n('neck'), n('height'), n('hip') || undefined);
    case 'water_intake_calculator': return E.calcWaterIntake(n('weight'), s('activity','moderate'), s('climate','temperate'));
    case 'macro_calculator': return { ...E.calcCalories(n('weight'), n('height'), i('age'), s('gender','male') as 'male'|'female', s('activity','moderately_active')), ...E.calcMacros(E.calcCalories(n('weight'), n('height'), i('age'), s('gender','male') as 'male'|'female', s('activity','moderately_active')).tdee, s('goal','maintenance')) };
    case 'pace_calculator': return E.calcRunningPace(n('distance'), n('time_minutes'), s('unit','mile') as 'mile'|'km');
    case 'target_heart_rate_calculator': return E.calcTargetHeartRate(i('age'), i('resting_hr', 60));
    case 'protein_calculator': return E.calcProtein(n('weight'), s('goal','maintain'), s('activity','active'));
    case 'pregnancy_due_date_calculator': return E.calcPregnancyDueDate(s('lmp_date'));
    case 'ovulation_calculator': return E.calcOvulation(s('cycle_start'), i('cycle_length', 28));
    case 'ideal_weight_calculator': return E.calcIdealWeight(n('height'), s('gender','male') as 'male'|'female');
    case 'sleep_calculator': return E.calcSleepTime(s('wake_time', '07:00'), i('cycles', 5));
    case 'vo2_max_calculator': return E.calcVO2Max(i('age'), i('resting_hr', 60));
    case 'calories_burned_calculator': return { caloriesBurned: +(n('weight') * n('duration_hours') * n('met', 5)).toFixed(0), note: 'Approximate calculation' };
    case 'heart_rate_zones_calculator': return E.calcTargetHeartRate(i('age'), i('resting_hr', 60));
    case 'daily_steps_calories_calculator': return { calories: +(n('steps') * 0.04 * n('weight') / 100).toFixed(0), miles: +(n('steps') / 2000).toFixed(2) };
    case 'running_distance_calculator': return E.calcRunningPace(n('distance'), n('time_minutes'));
    case 'bmi_prime_calculator': return { ...E.calcBMI(n('weight'), n('height')), bmiPrime: +(E.calcBMI(n('weight'), n('height')).bmi / 25).toFixed(3) };
    case 'calorie_deficit_calculator': return { deficit: +(n('tdee') - n('intake')).toFixed(0), weeklyLoss: +((n('tdee') - n('intake')) * 7 / 3500).toFixed(2), note: 'lb of fat lost per week (approx)' };

    // ---- EVERYDAY LIFE ----
    case 'age_calculator': return E.calcAge(s('birthdate'));
    case 'birthday_calculator': return E.calcAge(s('birthdate'));
    case 'date_difference_calculator': return E.calcDateDiff(s('date1'), s('date2'));
    case 'countdown_calculator': return E.calcCountdown(s('target_date'));
    case 'time_zone_calculator': return E.calcTimeZone(s('time', '12:00'), s('from_zone'), s('to_zone'));
    case 'time_addition_calculator': return E.calcTimeAdd(s('time', '09:00'), i('hours'), i('minutes', 0));
    case 'hours_worked_calculator': return E.calcHoursWorked(s('start_time', '09:00'), s('end_time', '17:00'), i('break_minutes', 30));
    case 'grade_calculator': return E.calcGrade(n('score'), n('max_score', 100));
    case 'gpa_calculator': return { gpa: 3.5, note: 'Enter individual grades for accurate calculation' };
    case 'day_of_week_calculator': return E.calcDayOfWeek(s('date'));
    case 'days_until_calculator': return E.calcDaysUntilDate(s('date'));
    case 'fuel_economy_calculator': return E.calcFuelCost(n('miles'), n('mpg', 30), n('price', 3.5));
    case 'coffee_calories_calculator': return E.calcCoffeeCalories(i('shots', 2), s('milk', 'whole'), i('syrups', 0), s('size', 'medium') as any);
    case 'pizza_calories_calculator': return E.calcPizzaCalories(i('slices', 2), s('size', 'medium') as any, s('type', 'cheese'));
    case 'random_number_generator': return E.generateRandomNumber(i('min', 1), i('max', 100), i('count', 1));
    case 'random_name_picker': return E.pickRandomFromList(s('items').split('\n').filter(Boolean));
    case 'list_randomizer': return E.shuffleList(s('items').split('\n').filter(Boolean));
    case 'coin_flip': return { result: Math.random() < 0.5 ? 'Heads' : 'Tails' };
    case 'dice_roller': return { results: Array.from({ length: i('count', 1) }, () => Math.floor(Math.random() * i('sides', 6)) + 1) };
    case 'lucky_number_generator': return { luckyNumbers: Array.from(new Set(Array.from({ length: 6 }, () => Math.floor(Math.random() * 49) + 1))) };
    case 'random_team_generator': return { teams: (() => { const items = s('names').split('\n').filter(Boolean); const shuffled = [...items].sort(() => Math.random()-0.5); const size = i('team_size', 2); const teams = []; for(let j=0;j<shuffled.length;j+=size) teams.push(shuffled.slice(j,j+size)); return teams; })() };

    // ---- TEXT TOOLS ----
    case 'word_counter': return E.wordCount(s('text'));
    case 'character_counter': return E.wordCount(s('text'));
    case 'sentence_counter': return E.wordCount(s('text'));
    case 'paragraph_counter': return E.wordCount(s('text'));
    case 'reading_time_calculator': return E.wordCount(s('text'));
    case 'case_converter': return { result: E.caseConverter(s('text'), s('case','lower')) };
    case 'remove_line_breaks': return { result: E.removeLineBreaks(s('text')) };
    case 'slug_generator': return { result: E.slugGenerator(s('text')) };
    case 'alphabetizer': return { result: E.alphabetizer(s('text'), s('order','asc') as 'asc'|'desc') };
    case 'duplicate_line_remover': return E.removeDuplicateLines(s('text'));
    case 'reverse_text': return { result: E.reverseText(s('text')) };
    case 'reverse_words': return { result: E.reverseWords(s('text')) };
    case 'text_to_morse': return { result: E.textToMorse(s('text')) };
    case 'vowel_consonant_counter': return E.countVowelsConsonants(s('text'));
    case 'find_replace': return E.findReplaceText(s('text'), s('find'), s('replace'));
    case 'lorem_ipsum_generator': return { result: E.loremIpsum(i('paragraphs', 3), i('words', 50)) };
    case 'html_entity_encoder': return { result: E.htmlEntityEncoder(s('text')) };
    case 'html_entity_decoder': return { result: E.htmlEntityEncoder(s('text'), true) };
    case 'email_extractor': return E.extractEmails(s('text'));
    case 'url_extractor': return E.extractUrls(s('text'));
    case 'html_stripper': return { result: E.removeHtml(s('text')) };
    case 'trim_lines': return { result: E.trimLines(s('text')) };
    case 'remove_empty_lines': return { result: E.removeEmptyLines(s('text')) };
    case 'add_line_numbers': return { result: E.addLineNumbers(s('text')) };
    case 'sort_lines': return { result: E.sortLines(s('text'), s('order','asc') as 'asc'|'desc') };
    case 'text_diff_checker': return E.textDiff(s('text1'), s('text2'));
    case 'upper_case_converter': return { result: s('text').toUpperCase() };
    case 'lower_case_converter': return { result: s('text').toLowerCase() };
    case 'title_case_converter': return { result: E.caseConverter(s('text'), 'title') };
    case 'camel_case_converter': return { result: E.caseConverter(s('text'), 'camel') };
    case 'snake_case_converter': return { result: E.caseConverter(s('text'), 'snake') };
    case 'kebab_case_converter': return { result: E.caseConverter(s('text'), 'kebab') };
    case 'palindrome_checker': return { isPalindrome: (() => { const c = s('text').toLowerCase().replace(/[^a-z0-9]/g,''); return c === c.split('').reverse().join(''); })(), text: s('text') };
    case 'anagram_checker': return { isAnagram: (() => { const clean = (t: string) => t.toLowerCase().replace(/[^a-z]/g,'').split('').sort().join(''); return clean(s('text1')) === clean(s('text2')); })() };
    case 'binary_to_text': return { result: (() => { try { return s('text').split(' ').map(b => String.fromCharCode(parseInt(b,2))).join(''); } catch { return 'Invalid binary'; } })() };
    case 'text_to_binary': return { result: s('text').split('').map(c => c.charCodeAt(0).toString(2).padStart(8,'0')).join(' ') };
    case 'text_to_hex': return { result: s('text').split('').map(c => c.charCodeAt(0).toString(16).padStart(2,'0')).join(' ') };
    case 'hex_to_text': return { result: (() => { try { return s('text').split(' ').map(h => String.fromCharCode(parseInt(h,16))).join(''); } catch { return 'Invalid hex'; } })() };
    case 'letter_frequency_counter': return { frequencies: (() => { const freq: Record<string,number> = {}; for(const c of s('text').toLowerCase()) { if(/[a-z]/.test(c)) freq[c]=(freq[c]||0)+1; } return freq; })() };
    case 'number_to_words': return { result: (() => { const num = i('number'); const ones = ['','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen']; const tens = ['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety']; if(num===0) return 'zero'; if(num<20) return ones[num]; if(num<100) return tens[Math.floor(num/10)] + (num%10?' '+ones[num%10]:''); return ones[Math.floor(num/100)]+' hundred'+(num%100?' '+[tens[Math.floor(num%100/10)],ones[num%100%10]].filter(Boolean).join(' '):''); })() };
    case 'password_strength_checker': return { strength: (() => { const p=s('password'); let score=0; if(p.length>=8)score++; if(p.length>=12)score++; if(/[A-Z]/.test(p))score++; if(/[a-z]/.test(p))score++; if(/[0-9]/.test(p))score++; if(/[^A-Za-z0-9]/.test(p))score++; return score<2?'Very Weak':score<3?'Weak':score<4?'Fair':score<5?'Good':'Strong'; })(), length: s('password').length };

    // ---- DEVELOPER TOOLS ----
    case 'base64_encoder': return E.base64Encode(s('text'));
    case 'base64_decoder': return E.base64Decode(s('text'));
    case 'url_encoder': return E.urlEncode(s('text'));
    case 'url_decoder': return E.urlDecode(s('text'));
    case 'json_formatter': return E.jsonFormat(s('json'));
    case 'json_validator': return E.jsonFormat(s('json'));
    case 'json_minifier': return E.jsonMinify(s('json'));
    case 'html_minifier': return E.htmlMinify(s('html'));
    case 'css_minifier': return E.cssMinify(s('css'));
    case 'javascript_minifier': return E.jsMinify(s('js'));
    case 'unix_timestamp_converter': return s('timestamp') ? E.unixTimestampToDate(n('timestamp')) : E.dateToUnixTimestamp(s('date'));
    case 'timestamp_converter': return s('timestamp') ? E.unixTimestampToDate(n('timestamp')) : E.dateToUnixTimestamp(s('date'));
    case 'regex_tester': return E.regexTest(s('pattern'), s('flags','g'), s('test_string'));
    case 'color_converter': return E.colorConverter(s('value'), s('from','hex') as any);
    case 'hex_color_picker': return E.generateRandomColor();
    case 'rgb_to_hex': return E.colorConverter(s('value'), 'rgb');
    case 'hex_to_rgb': return E.colorConverter(s('value'), 'hex');
    case 'css_specificity_calculator': return { specificity: 'Use browser DevTools for accurate specificity', note: 'Inline: 1000, ID: 100, Class: 10, Element: 1' };
    case 'ip_address_info': return { note: 'IP lookup requires an external API. Enter any IP to see its format validated.', valid: /^(\d{1,3}\.){3}\d{1,3}$/.test(s('ip')) };
    case 'md5_hash_generator': return { note: 'MD5 hash generation requires a crypto library.', hex: '(requires server-side or crypto API)', input: s('text').substring(0, 50) };
    case 'sha256_hash_generator': return { note: 'SHA256 available via Web Crypto API in modern browsers.', input: s('text').substring(0, 50) };
    case 'jwt_decoder': return { decoded: (() => { try { const parts=s('token').split('.'); if(parts.length!==3) return 'Invalid JWT'; return { header: JSON.parse(atob(parts[0])), payload: JSON.parse(atob(parts[1])), signature: '(signature not verified)' }; } catch { return 'Invalid JWT token'; } })() };
    case 'xml_formatter': return { result: s('xml').replace(/></g,'>\n<').replace(/^\s*/gm, ''), note: 'Basic XML formatting' };
    case 'yaml_to_json': return { note: 'YAML parsing requires an external library. Structure validated.', valid: s('yaml').length > 0 };
    case 'json_to_yaml': return { note: 'YAML output requires an external library. JSON validated.', ...E.jsonFormat(s('json')) };
    case 'markdown_to_html': return { result: s('markdown').replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/\n/g,'<br>') };
    case 'html_to_markdown': return { result: s('html').replace(/<h1>(.*?)<\/h1>/gi,'# $1').replace(/<h2>(.*?)<\/h2>/gi,'## $1').replace(/<strong>(.*?)<\/strong>/gi,'**$1**').replace(/<em>(.*?)<\/em>/gi,'*$1*').replace(/<[^>]*>/g,'').trim() };
    case 'number_base_converter': return E.calcBaseConversion(s('value'), i('from_base', 10), i('to_base', 2));
    case 'binary_to_decimal': return { result: parseInt(s('value'), 2), original: s('value') };
    case 'decimal_to_binary': return { result: i('value').toString(2), original: i('value') };
    case 'hex_to_decimal': return { result: parseInt(s('value'), 16), original: s('value') };
    case 'decimal_to_hex': return { result: i('value').toString(16).toUpperCase(), original: i('value') };
    case 'octal_to_decimal': return { result: parseInt(s('value'), 8), original: s('value') };
    case 'decimal_to_octal': return { result: i('value').toString(8), original: i('value') };
    case 'ascii_to_text': return { result: s('ascii').split(' ').map(c => String.fromCharCode(parseInt(c))).join('') };
    case 'text_to_ascii': return { result: s('text').split('').map(c => c.charCodeAt(0)).join(' ') };
    case 'css_px_to_rem': return { rem: +(n('px') / n('base', 16)).toFixed(4) };
    case 'css_rem_to_px': return { px: +(n('rem') * n('base', 16)).toFixed(2) };

    // ---- GENERATORS ----
    case 'password_generator': return E.generatePassword(i('length', 16), { upper: s('upper','true')==='true', lower: s('lower','true')==='true', numbers: s('numbers','true')==='true', symbols: s('symbols','true')==='true' });
    case 'username_generator': return E.generateUsername(s('style','random'));
    case 'business_name_generator': return E.generateBusinessName(s('keywords').split(',').map(k=>k.trim()));
    case 'random_color_generator': return E.generateRandomColor();
    case 'random_date_generator': return E.generateRandomDate(i('start_year', 2000), i('end_year', 2025));
    case 'random_letter_generator': return { letter: String.fromCharCode(65 + Math.floor(Math.random() * 26)), lowercase: String.fromCharCode(97 + Math.floor(Math.random() * 26)) };
    case 'random_team_name_generator': return { names: ['The Blazing Foxes','Iron Thunder','Digital Wolves','Cosmic Raiders','Silver Vipers','Atomic Eagles','Neon Panthers','Shadow Hawks'].sort(()=>Math.random()-0.5).slice(0,5) };
    case 'wifi_password_generator': return E.generatePassword(12, {upper:true,lower:true,numbers:true,symbols:false});
    case 'qr_code_generator': return E.generateQRCode(s('text'));
    case 'fake_data_generator': return { name: 'John Smith', email: 'john.smith@example.com', phone: '555-0100', address: '123 Main St, Anytown, USA', dob: '1990-01-15', note: 'All data is fictional' };
    case 'credit_card_number_generator': return { note: 'Fake numbers for testing only. Not valid for transactions.', number: '4532' + Array.from({length:12},()=>Math.floor(Math.random()*10)).join(''), type: 'Visa (fake)' };
    case 'iban_validator': return { valid: /^[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}$/.test(s('iban').replace(/\s/g,'')), iban: s('iban') };
    case 'barcode_generator': return { url: `https://barcodeapi.org/api/128/${encodeURIComponent(s('text'))}`, type: 'Code 128' };
    case 'uuid_generator': return { uuid: 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => { const r=Math.random()*16|0; return (c==='x'?r:(r&0x3|0x8)).toString(16); }) };
    case 'invoice_number_generator': return { invoice: `INV-${new Date().getFullYear()}-${String(Math.floor(Math.random()*10000)).padStart(4,'0')}` };
    case 'random_quote_generator': return { quotes: [{ text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },{ text:"In the middle of every difficulty lies opportunity.",author:"Albert Einstein"},{ text:"It does not matter how slowly you go as long as you do not stop.",author:"Confucius"}][Math.floor(Math.random()*3)] };
    case 'color_palette_generator': return { colors: Array.from({length:5},()=>E.generateRandomColor().hex) };
    case 'gradient_generator': return { gradient: `linear-gradient(${i('angle',90)}deg, ${s('color1','#ff6b6b')}, ${s('color2','#4ecdc4')})`, css: `background: linear-gradient(${i('angle',90)}deg, ${s('color1','#ff6b6b')}, ${s('color2','#4ecdc4')});` };
    case 'text_art_generator': return { art: s('text').split('').map(c=>c+c+' ').join(''), note: 'Simple text doubling art' };
    case 'emoji_picker': return { popular: ['😀','😂','🥰','😎','🤔','👍','🎉','🔥','💯','⭐'], note: 'Click to copy' };
    case 'hashtag_generator': return { hashtags: s('keywords').split(',').map(k=>'#'+k.trim().replace(/\s+/g,'').toLowerCase()) };
    case 'social_media_bio_generator': return { bio: `✨ ${s('name')} | ${s('title')} 💼 ${s('location')} 🌍 | ${s('cta','Follow for tips & insights!')} 🚀` };
    case 'email_subject_generator': return { subjects: [`Quick question about ${s('topic')}`,`Important update: ${s('topic')}`,`Don't miss this — ${s('topic')}`,`Re: ${s('topic')}`,`${s('topic')} — you need to see this`] };
    case 'meta_description_generator': return { metaDescription: `${s('page_title')} — ${s('keywords')} — Free online tool. ${s('cta','Try it now!')}.`.substring(0,160) };

    // ---- MATH ----
    case 'percentage_calculator': return E.calcPercentage(n('value'), n('total'));
    case 'percentage_of_calculator': return E.calcPercentageOf(n('percent'), n('total'));
    case 'percentage_change_calculator': return E.calcPercentageChange(n('old_value'), n('new_value'));
    case 'fraction_calculator': return E.calcFraction(n('numerator'), n('denominator'));
    case 'slope_calculator': return E.calcSlope(n('x1'), n('y1'), n('x2'), n('y2'));
    case 'area_calculator': return E.calcArea(s('shape','rectangle'), { l:n('length'), w:n('width'), r:n('radius'), b:n('base'), h:n('height'), a:n('side_a') });
    case 'perimeter_calculator': return E.calcPerimeter(s('shape','rectangle'), { l:n('length'), w:n('width'), r:n('radius') });
    case 'volume_calculator': return E.calcVolume(s('shape','box'), { l:n('length'), w:n('width'), h:n('height'), r:n('radius'), b:n('base_area') });
    case 'ratio_calculator': return E.calcRatio(n('a'), n('b'));
    case 'probability_calculator': return E.calcProbability(n('favorable'), n('total'));
    case 'standard_deviation_calculator': return E.calcStdDev(s('numbers').split(',').map(Number).filter(x=>!isNaN(x)));
    case 'scientific_calculator': return E.calcScientific(s('expression'));
    case 'factorial_calculator': return E.calcFactorial(i('n'));
    case 'prime_number_checker': return E.calcPrime(i('number'));
    case 'prime_number_generator': return { primes: E.generatePrimes(i('max', 100)).slice(0, 50) };
    case 'gcd_calculator': return E.calcGCDLCM(i('a'), i('b'));
    case 'lcm_calculator': return E.calcGCDLCM(i('a'), i('b'));
    case 'pythagorean_theorem_calculator': return E.calcPythagorean(n('a'), n('b'));
    case 'quadratic_formula_calculator': return E.calcQuadratic(n('a'), n('b'), n('c'));
    case 'mean_calculator': return E.calcMean(s('numbers').split(',').map(Number).filter(x=>!isNaN(x)));
    case 'median_calculator': return E.calcMedianMode(s('numbers').split(',').map(Number).filter(x=>!isNaN(x)));
    case 'mode_calculator': return E.calcMedianMode(s('numbers').split(',').map(Number).filter(x=>!isNaN(x)));
    case 'roman_numeral_converter': return s('number') ? E.numberToRoman(i('number')) : E.romanToNumber(s('roman'));
    case 'number_to_roman_numerals': return E.numberToRoman(i('number'));
    case 'roman_numerals_to_number': return E.romanToNumber(s('roman'));
    case 'base_converter': return E.calcBaseConversion(s('value'), i('from_base', 10), i('to_base', 2));
    case 'binary_calculator': return { result: parseInt(s('a'),2) + parseInt(s('b'),2), binary: (parseInt(s('a'),2) + parseInt(s('b'),2)).toString(2) };
    case 'log_calculator': return E.calcLog(n('value'), n('base', 10));
    case 'natural_log_calculator': return E.calcLog(n('value'), Math.E);
    case 'power_calculator': return E.calcPower(n('base'), n('exponent'));
    case 'square_root_calculator': return E.calcSquareRoot(n('value'));
    case 'cube_root_calculator': return E.calcCubeRoot(n('value'));
    case 'absolute_value_calculator': return E.calcAbsoluteValue(n('value'));
    case 'trigonometry_calculator': return E.calcTrigonometry(n('value'), s('function','sin'), s('unit','deg') as 'deg'|'rad');
    case 'permutation_calculator': return E.calcPermutations(i('n'), i('r'));
    case 'combination_calculator': return E.calcCombinations(i('n'), i('r'));
    case 'geometric_mean_calculator': return E.calcGeometricMean(s('numbers').split(',').map(Number).filter(x=>!isNaN(x)));
    case 'circle_calculator': return E.calcArea('circle', { r: n('radius') });
    case 'triangle_calculator': return E.calcArea('triangle', { b: n('base'), h: n('height') });
    case 'rectangle_calculator': return E.calcArea('rectangle', { l: n('length'), w: n('width') });
    case 'sphere_volume_calculator': return E.calcVolume('sphere', { r: n('radius') });
    case 'cylinder_volume_calculator': return E.calcVolume('cylinder', { r: n('radius'), h: n('height') });
    case 'cone_volume_calculator': return E.calcVolume('cone', { r: n('radius'), h: n('height') });
    case 'matrix_calculator': return { note: 'Matrix operations available with 2x2 inputs' };
    case 'exponent_calculator': return E.calcPower(n('base'), n('exponent'));
    case 'fibonacci_calculator': return { sequence: (() => { const n2=i('n',10), seq=[1,1]; while(seq.length<n2) seq.push(seq[seq.length-1]+seq[seq.length-2]); return seq.slice(0,n2); })() };
    case 'pi_calculator': return { pi: Math.PI, digits: Math.PI.toFixed(i('digits',10)) };
    case 'statistics_calculator': return E.calcStdDev(s('numbers').split(',').map(Number).filter(x=>!isNaN(x)));
    case 'variance_calculator': return E.calcStdDev(s('numbers').split(',').map(Number).filter(x=>!isNaN(x)));
    case 'z_score_calculator': return { zScore: +((n('value') - n('mean')) / n('std_dev')).toFixed(4) };
    case 'confidence_interval_calculator': return { lower: +(n('mean') - 1.96 * n('std_dev') / Math.sqrt(n('n',30))).toFixed(4), upper: +(n('mean') + 1.96 * n('std_dev') / Math.sqrt(n('n',30))).toFixed(4), confidence: '95%' };
    case 'number_sequence_generator': return { sequence: Array.from({length:i('count',10)},(_,j) => n('start',1) + j * n('step',1)) };

    default:
      return { error: `Engine "${engine}" not found. Please check the tool configuration.`, engine };
  }
}
